### ISSUE TITLE
Python 3.11 support, or sunsetting status documentation

### ISSUE THREAD

**Issue by econtal** [jcrudy/choldate#6]
7 years after the last commit, I'm still using this library!

Unfortunately it doesn't compile in python 3.11. Could you clarify whether the library will be maintained, or if it's being sunset?

I can compile in Python 3.10, but not 3.11:

```python
      choldate/_choldate.c:107:11: error: too few arguments to function ‘PyCode_New’
        107 |           PyCode_New(a, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
            |           ^~~~~~~~~~
```
and
```python
      choldate/_choldate.c: In function ‘__Pyx_AddTraceback’:
      choldate/_choldate.c:6338:13: error: invalid use of incomplete typedef ‘PyFrameObject’ {aka ‘struct _frame’}
       6338 |     py_frame->f_lineno = py_line;
            |             ^~
```

**Comment by econtal** [comment]
Actually it might be related to #7 which is fixed with #8
